version: '3.7'

services:
  pomelo-code-test:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - /opt/app/node_modules
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
